chore(ci): Refactor workflow

diff --git a/.github/workflows/cache.yml b/.github/workflows/cache.yml
--- a/.github/workflows/cache.yml
+++ b/.github/workflows/cache.yml
@@ -3,32 +3,93 @@ name: Build flake outputs and cache binaries on cachix
 on:
   workflow_call:
     inputs:
-      runs_on:
+      targets:
         required: true
         type: string
-      target:
+    secrets:
+      cachix-auth-token:
         required: true
-        type: string
+
 
 env:
   NIXPKGS_ALLOW_UNFREE: 1
 
 jobs:
   cache:
-    runs-on: ${{ inputs.runs_on }}
+    name: Build targets
+
+    strategy:
+      fail-fast: false
+      matrix:
+        runs-on:
+          - macos-latest  # X64-macOS
+          - ubuntu-latest # X64-Linux
+
+    outputs:
+      X64-macOS: ${{ steps.output.outputs.X64-macOS }}
+      X64-Linux: ${{ steps.output.outputs.X64-Linux }}
+
+    runs-on: ${{ matrix.runs-on }}
+
     steps:
-      - uses: actions/checkout@v2.4.0
+      - uses: actions/checkout@v3
       - uses: cachix/install-nix-action@v18
         with:
           nix_path: nixpkgs=channel:nixos-unstable
-          extra_nix_config: |
-            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
-      - uses: cachix/cachix-action@v11
+          extra_nix_config: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
+
+      - name: Check if the targets can be built
+        run: nix build --dry-run ${{ inputs.targets }}
+        id: check-buildable
+        continue-on-error: true
+
+      - name: Setup cachix
+        uses: cachix/cachix-action@v12
         with:
           name: aiotter
-          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
+          authToken: ${{ secrets.cachix-auth-token }}
+        if: ${{ steps.check-buildable.outcome == 'success' }}
 
-      - run: nix build ${{ inputs.target }}
-        id: build
-      - run: nix log ${{ inputs.target }}
-        if: ${{ failure() && steps.build.conclusion == 'failure' }}
+      - name: Build
+        run: nix build --log-lines 99999 ${{ inputs.targets }}
+        if: ${{ steps.check-buildable.outcome == 'success' }}
+
+      # runner.arch is one of: [X86, X64, ARM, ARM64]
+      # runner.os is one of: [Linux, Windows, macOS]
+      - name: Set output (${{ runner.arch }}-${{ runner.os }})
+        run: echo "${{ runner.arch }}-${{ runner.os }}=true" >>$GITHUB_OUTPUT
+        id: output
+        if: ${{ steps.check-buildable.outcome == 'success' }}
+
+      - name: Create job summary
+        run: |
+          RESULT='${{ steps.check-buildable.outcome != 'success' && 'Skipped' || ( job.status == 'success' && '⭕️ Success' || '❌ Failure' ) }}'
+          function create-list () {
+            for i in "$@"; do
+              echo '- `'$i'` '
+            done
+          }
+          cat <<EOF >>$GITHUB_STEP_SUMMARY
+          ## $(nix eval --expr builtins.currentSystem --impure --raw)
+          ### ${RESULT}
+          $(create-list ${{ inputs.targets }})
+          EOF
+        if: ${{ success() || failure() }}
+
+  not-built:
+    needs: cache
+    if: ${{ !contains(needs.cache.outputs.*, 'true') }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Output error
+        run: echo "::error title=Not built::No target for any of the runners!"; false
+
+  check:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: cachix/install-nix-action@v18
+        with:
+          nix_path: nixpkgs=channel:nixos-unstable
+          extra_nix_config: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
+      - run: nix flake check
